FROM python:3.13-slim@sha256:a93b51c5acbd72f9d28fd811a230c67ed59bcd727ac08774dee4bbf64b7630c7

# Install dependencies
WORKDIR /tmp

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt \
    && rm -rf requirements.txt

# Copy source code
WORKDIR /app
# Copy current directory contents into vllm_router subdirectory to match package name expected by imports
COPY . vllm_router/

# Set PYTHONPATH so python can find the vllm_router package
ENV PYTHONPATH=/app

# Copy git revision file (generated by build-image.sh)
COPY --chmod=664 .GIT_REV /etc/

# Default entrypoint
ENTRYPOINT ["python3", "-m", "vllm_router.app"]
