FROM python:3.13-slim@sha256:a93b51c5acbd72f9d28fd811a230c67ed59bcd727ac08774dee4bbf64b7630c7

# Install dependencies
WORKDIR /tmp

# Set SOURCE_DATE_EPOCH for reproducible builds
ARG SOURCE_DATE_EPOCH=0
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
ENV PYTHONDONTWRITEBYTECODE=1

COPY requirements.txt ./
RUN pip install --no-cache-dir --no-compile --upgrade -r requirements.txt \
    && rm -rf requirements.txt \
    && find /usr/local/lib/python3.13/site-packages -type f -name '*.pyc' -delete \
    && find /usr/local/lib/python3.13/site-packages -type f -name '*.pyo' -delete \
    && find /usr/local/lib/python3.13/site-packages -type d -name '__pycache__' -delete

# Copy source code
WORKDIR /app
# Copy git revision file first (generated by build-image.sh)
COPY .GIT_REV /etc/.GIT_REV
# Copy current directory contents into vllm_router subdirectory to match package name expected by imports
COPY . vllm_router/

# Set PYTHONPATH so python can find the vllm_router package
ENV PYTHONPATH=/app

# Default entrypoint
ENTRYPOINT ["python3", "-m", "vllm_router.app"]
